import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  BookOpen, Layers, Database, CheckCircle, Code, ArrowRight,
  Copy, FileText, Plus, AlertTriangle, BookOpenCheck, Zap,
  GitBranch, RefreshCw, Globe, Server, CloudLightning, ShieldCheck,
  Terminal, Play, Check, X, Star, Heart, Award, Compass, Laptop, Rocket
} from 'lucide-react';

/* ─────────────────────────────── helpers ─────────────────────────────── */
const Section = ({ eyebrow, title, children }) => (
  <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="learning-card">
    <div style={{ marginBottom: '1.5rem' }}>
      <span style={{ color: '#6366f1', fontWeight: 600, fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{eyebrow}</span>
      <h2 style={{ fontSize: '2rem', marginTop: '0.5rem', color: '#0f172a' }}>{title}</h2>
    </div>
    {children}
  </motion.div>
);

const CodeBlock = ({ title, code }) => {
  const [cp, setCp] = useState(false);
  const hlJS = (c) => {
    let h = c.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    h = h.replace(/(\/\/[^\n]*)/g, '<span style="color:#8892b0">$1</span>');
    h = h.replace(/(["'`])([\s\S]*?)\1/g, '<span style="color:#a5d6ff">$1$2$1</span>');
    ['const','let','var','return','import','export','default','function','from','if','else','async','await','try','catch','throw','new','true','false','null','undefined'].forEach(k => {
      h = h.replace(new RegExp(`\\b(${k})\\b`, 'g'), '<span style="color:#ff7b72;font-weight:bold">$1</span>');
    });
    return <span dangerouslySetInnerHTML={{ __html: h }} />;
  };
  return (
    <div style={{ background: '#0f172a', borderRadius: 12, border: '1px solid #1e293b', margin: '1.2rem 0', overflowX: 'auto' }}>
      {title && (
        <div style={{ background: '#1e293b', padding: '0.5rem 1rem', fontSize: '0.8rem', color: '#94a3b8', borderBottom: '1px solid #334155', display: 'flex', justifyContent: 'space-between' }}>
          <span>{title}</span>
          <button onClick={() => { navigator.clipboard.writeText(code); setCp(true); setTimeout(() => setCp(false), 2000); }}
            style={{ background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: 4 }}>
            <Copy size={12} /> {cp ? 'Copied!' : 'Copy'}
          </button>
        </div>
      )}
      <pre style={{ margin: 0, padding: '1rem', color: '#f8fafc', fontSize: '0.88rem', fontFamily: 'monospace', lineHeight: 1.6, whiteSpace: 'pre' }}>
        <code>{hlJS(code)}</code>
      </pre>
    </div>
  );
};

/* ─────────────────────────────── main component ──────────────────────── */
export default function ReactDay15({ activeTab, onNavigate }) {
  const go = (id) => { onNavigate('react_module15', id); window.scrollTo({ top: 0, behavior: 'smooth' }); };

  /* ── Section 2: Deployment checklist ── */
  const [checklist, setChecklist] = useState({
    logs: true,
    env: false,
    build: false,
    routing: false
  });
  const toggleCheck = (k) => setChecklist(p => ({ ...p, [k]: !p[k] }));

  /* ── Capstone Task: Interactive Console Deployment simulator ── */
  const [activeDeploy, setActiveDeploy] = useState(null);
  const [deployStep, setDeployStep] = useState(0);
  const [deployLogs, setDeployLogs] = useState([]);
  const [deployedUrl, setDeployedUrl] = useState(null);

  const simulateDeploy = async (projectKey, title) => {
    setActiveDeploy(projectKey);
    setDeployedUrl(null);
    setDeployStep(0);
    setDeployLogs(['🚀 Initializing deployment pipeline for ' + title]);
    
    const steps = [
      '🔍 Validating dependency manifests (package.json)...',
      '⚙️ Executing build command: "npm run build"',
      '📦 Minifying code scripts & bundling CSS modules assets...',
      '📡 Uploading distribution folder (/dist) assets to cloud servers...',
      '🔒 Allocating free HTTPS SSL certificates protocols...',
      '✅ Deployment successful! Assigning domain URL...'
    ];

    for (let i = 0; i < steps.length; i++) {
      await new Promise(r => setTimeout(r, 600));
      setDeployStep(i + 1);
      setDeployLogs(p => [...p, steps[i]]);
    }

    const slugs = { sms: 'uni-sms', port: 'jane-portfolio', store: 'unistore', dash: 'edu-analytics' };
    setDeployedUrl(`https://${slugs[projectKey]}.vercel.app`);
  };

  /* ── Course Rating Survey ── */
  const [rating, setRating] = useState(5);
  const [surveySubmitted, setSurveySubmitted] = useState(false);

  /* ── Quiz ── */
  const [qAns, setQAns] = useState({});
  const [qDone, setQDone] = useState(false);
  const questions = [
    { k: 'q1', q: 'Which folder is generated by Vite when running the "npm run build" compilation command?',
      opts: ['/src', '/node_modules', '/dist', '/public'], ans: 2,
      exp: 'Vite compiles all files and outputs static minified files under the "/dist" (distribution) folder for deployment.' },
    { k: 'q2', q: 'How do you prefix environment variables in a Vite project so React can read them?',
      opts: ['REACT_APP_', 'VITE_', 'PROCESS_ENV_', 'CONFIG_'], ans: 1,
      exp: 'Vite requires environment variables to be prefixed with "VITE_" (e.g. VITE_API_URL) to make them accessible via import.meta.env.' },
    { k: 'q3', q: 'What hosting providers are best suited for hosting static Single Page Applications (SPAs) like React?',
      opts: ['Vercel, Netlify, GitHub Pages', 'Apache TomCat Server', 'MongoDB Atlas cloud clusters', 'Docker Registry hub'],
      ans: 0, exp: 'Vercel, Netlify, and GitHub Pages are optimized static hosts that serve /dist folders with global CDNs and edge networks.' },
    { k: 'q4', q: 'When deploying a React Router SPA, why does refreshing a sub-page (e.g., /dashboard) return a 404 error on simple static servers?',
      opts: [
        'Because the React Router package is deleted during builds',
        'Because the static server tries to locate a physical file at "/dashboard" which does not exist. All routes must fallback to index.html.',
        'Because the browser does not support client routing redirects',
        'Due to CORS permission access blocks'
      ], ans: 1,
      exp: 'SPAs map all routes in client code. Static hosts need redirection configurations (like a redirects rule file) to forward all requests back to /index.html.' }
  ];
  const score = questions.filter(q => qAns[q.k] === q.ans).length;

  return (
    <AnimatePresence mode="wait">

      {/* ── 1. PROJECT COMPLETION & PRE-FLIGHT ───────────────────────────── */}
      {activeTab === 'intro_react' && (
        <Section key="s1" eyebrow="Module 01 • Day 15" title="Build & Production Prep">
          <div className="panel" style={{ color: '#334155', lineHeight: 1.8 }}>

            <div style={{ background: 'linear-gradient(135deg,#0ea5e9,#6366f1)', borderRadius: 16, padding: '2rem', marginBottom: '2rem' }}>
              <h3 style={{ fontSize: '1.4rem', fontWeight: 800, color: 'white', marginBottom: '0.75rem' }}>🚀 Production Compilation</h3>
              <p style={{ color: 'white', opacity: 0.95, margin: 0, lineHeight: 1.7 }}>
                Before deploying, React files must be compiled into optimized, minified HTML, CSS, and JS bundles that run instantly on browsers. Vite handles this compilation step using the <code>npm run build</code> command.
              </p>
            </div>

            <CodeBlock title="Production Environment Config (.env)" code={`// ── .env (Development file) ──────────────────────
VITE_API_URL=http://localhost:5000/api

// ── .env.production (Production file) ─────────────
VITE_API_URL=https://api.school.com/api

// ── Inside React JS components ────────────────────
useEffect(() => {
  // Vite injects environment variables here:
  fetch(import.meta.env.VITE_API_URL + "/students")
    .then(res => res.json())
    .then(setData);
}, []);`} />

            <h3 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.75rem' }}>Pre-flight Checklist</h3>
            <p>Complete these tasks before building your production bundle:</p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 8, background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: 14, padding: '1.25rem' }}>
              {[
                { k: 'logs', title: 'Clean Up Code logs', desc: 'Remove debugging console.logs, developer comments, and unused states.' },
                { k: 'env', title: 'Setup Environment keys', desc: 'Separate development endpoints from production domains.' },
                { k: 'build', title: 'Test Local builds', desc: 'Run npx vite build to catch import errors or broken brackets.' },
                { k: 'routing', title: 'Configure server fallbacks', desc: 'Add redirections rule files (e.g. _redirects for Netlify, vercel.json for Vercel).' }
              ].map(item => (
                <label key={item.k} style={{ display: 'flex', gap: 10, alignItems: 'flex-start', cursor: 'pointer', padding: '6px 0' }}>
                  <input type="checkbox" checked={checklist[item.k]} onChange={() => toggleCheck(item.k)} style={{ marginTop: 4, width: 15, height: 15 }} />
                  <div>
                    <strong style={{ display: 'block', color: '#0f172a', fontSize: '0.88rem' }}>{item.title}</strong>
                    <span style={{ fontSize: '0.78rem', color: '#64748b' }}>{item.desc}</span>
                  </div>
                </label>
              ))}
            </div>

            <div className="card-actions" style={{ marginTop: '2rem' }}>
              <button className="btn btn-primary" onClick={() => go('useState_hook')} style={{ background: '#6366f1', borderColor: '#6366f1' }}>
                Continue (+10 XP) <ArrowRight size={16} />
              </button>
            </div>
          </div>
        </Section>
      )}

      {/* ── 2. DEPLOYMENT METHODS ────────────────────────────────────────── */}
      {activeTab === 'useState_hook' && (
        <Section key="s2" eyebrow="Module 02 • Day 15" title="Hosting Providers">
          <div className="panel" style={{ color: '#334155', lineHeight: 1.8 }}>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', marginBottom: '2rem' }}>
              {[
                { name: 'Vercel', bestFor: 'React SPAs & Next.js frameworks', steps: ['Connect GitHub profile', 'Select React repository', 'Click Deploy (Auto builds)'], color: '#0f172a', bg: '#f1f5f9' },
                { name: 'Netlify', bestFor: 'Static websites & SPAs', steps: ['Connect Git repo', 'Configure Build command', 'Deploy (Auto generates domain)'], color: '#0ea5e9', bg: '#ecfdf5' },
                { name: 'GitHub Pages', bestFor: 'Simple personal repositories', steps: ['npm install gh-pages --save-dev', 'Configure homepage in package.json', 'Run: npm run deploy'], color: '#16a34a', bg: '#f0fdf4' }
              ].map((h, i) => (
                <div key={i} style={{ background: h.bg, border: `2px solid ${h.color}33`, borderRadius: 12, padding: '1.25rem' }}>
                  <strong style={{ display: 'block', fontSize: '1.1rem', color: '#0f172a', marginBottom: 4 }}>{h.name}</strong>
                  <span style={{ fontSize: '0.74rem', background: 'white', color: h.color, padding: '2px 8px', borderRadius: 4, fontWeight: 700, display: 'inline-block', marginBottom: 12 }}>Best for: {h.bestFor}</span>
                  <div style={{ fontSize: '0.8rem', color: '#374151' }}>
                    {h.steps.map((s, j) => <div key={j} style={{ marginBottom: 4 }}>{j + 1}. {s}</div>)}
                  </div>
                </div>
              ))}
            </div>

            <CodeBlock title="vercel.json — Router Redirection configuration" code={`{
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}`} />

            <CodeBlock title="_redirects — Netlify Redirection configuration" code={`/*    /index.html   200`} />

            <div className="card-actions" style={{ marginTop: '2rem' }}>
              <button className="btn btn-primary" onClick={() => go('multiple_states')} style={{ background: '#6366f1', borderColor: '#6366f1' }}>
                Continue (+10 XP) <ArrowRight size={16} />
              </button>
            </div>
          </div>
        </Section>
      )}

      {/* ── 3. CAPSTONE TASK: INTERACTIVE CONSOLE DEPLOYMENT SIMULATION ──── */}
      {activeTab === 'multiple_states' && (
        <Section key="s3" eyebrow="Capstone Task • Day 15" title="Interactive Deployment Pipeline">
          <div className="panel" style={{ color: '#334155', lineHeight: 1.8 }}>

            <div style={{ background: 'linear-gradient(135deg,#0ea5e9,#6366f1)', borderRadius: 14, padding: '1.5rem', marginBottom: '2rem' }}>
              <h3 style={{ fontWeight: 800, color: 'white', margin: '0 0 0.4rem', fontSize: '1.2rem' }}>🎓 Deploy Simulator</h3>
              <p style={{ color: 'white', opacity: 0.9, margin: 0, fontSize: '0.9rem', lineHeight: 1.6 }}>
                Select a mini project to run it through a simulated cloud build and deployment pipeline. Watch build logs compile in real time!
              </p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 8, marginBottom: '1.5rem' }}>
              {[
                { id: 'sms', title: 'Student Registry' },
                { id: 'port', title: 'Portfolio Builder' },
                { id: 'store', title: 'Product Store' },
                { id: 'dash', title: 'Metric Dashboard' }
              ].map(proj => (
                <button key={proj.id} onClick={() => simulateDeploy(proj.id, proj.title)} disabled={activeDeploy !== null && deployedUrl === null}
                  style={{
                    padding: '10px 0',
                    borderRadius: 8,
                    border: '1.5px solid #6366f1',
                    cursor: (activeDeploy !== null && deployedUrl === null) ? 'not-allowed' : 'pointer',
                    fontWeight: 700,
                    fontSize: '0.85rem',
                    background: activeDeploy === proj.id ? '#6366f1' : 'white',
                    color: activeDeploy === proj.id ? 'white' : '#6366f1',
                    transition: 'all 0.15s'
                  }}>
                  Deploy {proj.title}
                </button>
              ))}
            </div>

            {/* Simulated terminal logs display */}
            {activeDeploy && (
              <div style={{ background: '#0f172a', border: '1px solid #334155', borderRadius: 16, padding: '1.5rem', fontFamily: 'monospace', fontSize: '0.82rem', marginBottom: '1rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #1e293b', paddingBottom: 6, marginBottom: 10, color: '#64748b' }}>
                  <span>Build Terminal console</span>
                  <span>{deployStep === 7 ? 'COMPLETED' : 'BUILDING...'}</span>
                </div>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: 4, minHeight: 140 }}>
                  {deployLogs.map((log, i) => (
                    <div key={i} style={{ color: i === deployLogs.length - 1 ? '#86efac' : '#94a3b8' }}>
                      {log}
                    </div>
                  ))}
                </div>

                {deployedUrl && (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                    style={{ borderTop: '1px solid #1e293b', marginTop: 12, paddingTop: 12, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ color: '#38bdf8' }}>Mock Domain: <code>{deployedUrl}</code></span>
                    <a href={deployedUrl} target="_blank" rel="noopener noreferrer"
                      style={{ background: '#10b981', color: 'white', textDecoration: 'none', padding: '5px 12px', borderRadius: 6, fontWeight: 700, fontSize: '0.78rem' }}>
                      Visit Live Site →
                    </a>
                  </motion.div>
                )}
              </div>
            )}

            <div className="card-actions" style={{ marginTop: '2rem' }}>
              <button className="btn btn-primary" onClick={() => go('quiz')} style={{ background: '#6366f1', borderColor: '#6366f1' }}>
                Go to Quiz <ArrowRight size={16} />
              </button>
            </div>
          </div>
        </Section>
      )}

      {/* ── QUIZ ─────────────────────────────────────────────────────────── */}
      {activeTab === 'quiz' && (
        <Section key="quiz" eyebrow="Knowledge Check" title="Day 15 Quiz — Project Deployment">
          <div className="panel" style={{ color: '#334155', lineHeight: 1.8 }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.2rem' }}>
              {questions.map((item, qi) => (
                <div key={item.k} style={{ background: '#f8fafc', padding: '1.25rem', borderRadius: 12, border: '1px solid #cbd5e1' }}>
                  <p style={{ fontWeight: 700, color: '#1e293b', margin: '0 0 0.8rem' }}>{qi + 1}. {item.q}</p>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                    {item.opts.map((opt, oi) => {
                      const selected = qAns[item.k] === oi;
                      const correct = oi === item.ans;
                      let bg = 'white', border = '1px solid #cbd5e1';
                      if (qDone) {
                        if (correct) { bg = '#dcfce7'; border = '1.5px solid #10b981'; }
                        else if (selected) { bg = '#fee2e2'; border = '1.5px solid #ef4444'; }
                      } else if (selected) { bg = '#e0f2fe'; border = '1.5px solid #0ea5e9'; }
                      return (
                        <button key={oi} disabled={qDone} onClick={() => setQAns(p => ({ ...p, [item.k]: oi }))}
                          style={{ background: bg, border, padding: '0.6rem 1rem', borderRadius: 8, cursor: qDone ? 'default' : 'pointer', textAlign: 'left', fontSize: '0.88rem', transition: 'all 0.15s' }}>
                          {opt}
                        </button>
                      );
                    })}
                  </div>
                  {qDone && (
                    <div style={{ marginTop: '0.75rem', fontSize: '0.82rem', color: '#475569', fontStyle: 'italic', background: 'white', padding: '8px 12px', borderRadius: 6, borderLeft: '3px solid #6366f1' }}>
                      <strong>Explanation:</strong> {item.exp}
                    </div>
                  )}
                </div>
              ))}
              <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginTop: '0.5rem' }}>
                {!qDone ? (
                  <button className="btn btn-primary" onClick={() => setQDone(true)}
                    disabled={Object.keys(qAns).length < questions.length}
                    style={{ background: '#6366f1', borderColor: '#6366f1', minWidth: 150 }}>
                    Submit Answers
                  </button>
                ) : (
                  <>
                    <button className="btn btn-outline" onClick={() => { setQAns({}); setQDone(false); }} style={{ minWidth: 150 }}>Retry Quiz</button>
                    <div style={{ fontSize: '1.1rem', fontWeight: 800, color: score === questions.length ? '#10b981' : '#f59e0b' }}>
                      Score: {score} / {questions.length} ({Math.round(score / questions.length * 100)}%)
                    </div>
                  </>
                )}
              </div>
            </div>
            <div className="card-actions" style={{ marginTop: '2rem' }}>
              <button className="btn btn-primary" onClick={() => go('assignment')} style={{ background: '#6366f1', borderColor: '#6366f1' }}>
                Go to Final Review <ArrowRight size={16} />
              </button>
            </div>
          </div>
        </Section>
      )}

      {/* ── FINAL REVIEW / SURVEY ────────────────────────────────────────── */}
      {activeTab === 'assignment' && (
        <Section key="asgn" eyebrow="Course Complete" title="React JS Course Complete!">
          <div className="panel" style={{ color: '#334155', lineHeight: 1.8 }}>
            
            <div style={{ background: 'linear-gradient(135deg,#10b981,#059669)', borderRadius: 16, padding: '2rem', marginBottom: '2rem', textAlign: 'center' }}>
              <Award size={48} color="white" style={{ marginBottom: 10 }} />
              <h3 style={{ fontWeight: 800, fontSize: '1.6rem', color: 'white', margin: '0 0 0.5rem' }}>Congratulations!</h3>
              <p style={{ color: 'white', opacity: 0.9, margin: 0, fontSize: '0.95rem', lineHeight: 1.6 }}>
                You have completed the entire AI-Powered React JS course modules syllabus! From JavaScript ES6+ foundations, components lifecycle, states, Hooks configurations, API integrations, client routing, and cloud deployments.
              </p>
            </div>

            {/* Course Feedback Survey Form */}
            {!surveySubmitted ? (
              <div style={{ background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: 16, padding: '1.5rem', marginBottom: '1.5rem' }}>
                <h4 style={{ margin: '0 0 10px', color: '#0f172a', fontWeight: 800 }}>Course Experience Feedback</h4>
                <p style={{ fontSize: '0.85rem', color: '#64748b', margin: '0 0 1rem' }}>We value your opinion. Rate your overall course learning experience from 1 to 5 stars:</p>
                
                <div style={{ display: 'flex', gap: 6, marginBottom: '1.25rem' }}>
                  {[1, 2, 3, 4, 5].map(star => (
                    <button key={star} onClick={() => setRating(star)}
                      style={{ background: 'transparent', border: 'none', cursor: 'pointer', padding: 0 }}>
                      <Star size={30} fill={star <= rating ? '#fbbf24' : 'none'} color={star <= rating ? '#fbbf24' : '#cbd5e1'} />
                    </button>
                  ))}
                </div>

                <textarea className="form-control" placeholder="Write any additional comments or testimonials..." style={{ fontSize: '0.88rem', height: 80, marginBottom: '1rem', resize: 'none' }} />
                
                <button onClick={() => setSurveySubmitted(true)}
                  style={{ background: '#10b981', color: 'white', border: 'none', borderRadius: 8, padding: '8px 18px', fontWeight: 700, fontSize: '0.88rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6 }}>
                  <CheckCircle size={14} /> Submit Feedback
                </button>
              </div>
            ) : (
              <motion.div initial={{ scale: 0.95 }} animate={{ scale: 1 }}
                style={{ background: '#ecfdf5', border: '1px solid #a7f3d0', borderRadius: 16, padding: '1.5rem', textAlign: 'center', color: '#065f46', fontWeight: 700, marginBottom: '1.5rem' }}>
                <Heart size={32} fill="#ef4444" color="#ef4444" style={{ marginBottom: 8 }} />
                Thank you! Your feedback survey has been submitted successfully.
              </motion.div>
            )}

            <div style={{ background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: 12, padding: '1.5rem', textAlign: 'center' }}>
              <Laptop size={36} color="#10b981" style={{ marginBottom: '0.5rem' }} />
              <h5 style={{ fontWeight: 800, color: '#0f172a', margin: '0 0 0.25rem' }}>Next Steps: Capstone Submissions</h5>
              <p style={{ fontSize: '0.85rem', color: '#64748b', margin: 0 }}>Deploy your custom version of the four mini-projects using your personal Vercel or GitHub Pages profile. Submit the production links to your instructor.</p>
            </div>
          </div>
        </Section>
      )}
    </AnimatePresence>
  );
}
